apiVersion: v1
kind: Service
metadata:
  name: pxc-node3
  namespace: whitenfv
  labels:
    node: pxc-node3
spec:
  ports:
    - port: 3306
      name: mysql
    - port: 4444
      name: state-snapshot-transfer
    - port: 4567
      name: replication-traffic
    - port: 4568
      name: incremental-state-transfer
  selector:
    node: pxc-node2

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pxc-node3
  namespace: whitenfv
spec:
  replicas: 1
  template:
    metadata:
      labels:
        node: pxc-node3
        unit: pxc-cluster
    spec:
      nodeSelector:
        number: '2'
      containers:
        - image: capttofu/percona_xtradb_cluster_5_6:beta
          name: pxc-node3
          ports:
            - containerPort: 3306
            - containerPort: 4444
            - containerPort: 4567
            - containerPort: 4568
          envFrom:
          - secretRef:
              name: mysql-secret
          volumeMounts:
            - name: mysql-persistent-storage-3
              mountPath: /var/lib
          securityContext:
            capabilities: {}
            privileged: true #privileged required for mount

      volumes:
      - name: mysql-persistent-storage-3
        persistentVolumeClaim:
          claimName: claim-galera-3
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-galera-3
  namespace: whitenfv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      name: pxc3
