
apiVersion: v1
kind: Service
metadata:
  name: pxc-node3
  labels:
    node: pxc-node3
spec:
  ports:
    - port: 3306
      name: mysql
    - port: 4444
      name: state-snapshot-transfer
    - port: 4567
      name: replication-traffic
    - port: 4568
      name: incremental-state-transfer
  selector:
    node: pxc-node3

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pxc-node3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        node: pxc-node3
        unit: pxc-cluster
    spec:
      containers:
        - resources:
            limits:
              cpu: 0.3
          image: capttofu/percona_xtradb_cluster_5_6:beta
          name: pxc-node3
          ports:
            - containerPort: 3306
            - containerPort: 4444
            - containerPort: 4567
            - containerPort: 4568
          envFrom:
          - configMapRef:
              name: mysql-config
          volumeMounts:
            - name: mysql-persistent-storage-3
              mountPath: /var/lib
          securityContext:
            capabilities: {}
            privileged: true #privileged required for mount


       volumes:
       - name: mysql-persistent-storage-3
         persistentVolumeClaim:
           claimName: claim-galera-3

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-galera-3
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
